services:
  web:
    build:
      context: ./
    volumes:
      - .:/src
    command: supervisor -e '.' index.js
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - myNetwork
  db:
    image: mysql
    restart: always
     #env_file:
       #- ./.env
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sd2-db
    ports:
      - "3308:3306"
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - myNetwork
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    env_file:
      - ./.env
    ports:
      - "8081:80"
    networks:
      - myNetwork

networks:
  myNetwork:
    driver: bridge
